# Generated by Django 3.2.25 on 2025-05-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flooddata', 'initial_default_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demfile',
            name='file',
            field=models.FileField(upload_to='dem_files/', verbose_name='DEM файл'),
        ),
        migrations.AlterField(
            model_name='floodanalysis',
            name='flood_mask',
            field=models.FileField(blank=True, null=True, upload_to='analysis_results/', verbose_name='Маска затопления'),
        ),
        migrations.AlterField(
            model_name='satelliteimage',
            name='file',
            field=models.FileField(upload_to='satellite_images/', verbose_name='Космический снимок'),
        ),
        migrations.AddIndex(
            model_name='floodevent',
            index=models.Index(fields=['event_start', 'event_end'], name='flooddata_f_event_s_2cff25_idx'),
        ),
        migrations.AddIndex(
            model_name='floodevent',
            index=models.Index(fields=['is_forecast'], name='flooddata_f_is_fore_10d280_idx'),
        ),
        migrations.AddIndex(
            model_name='waterlevelmeasurement',
            index=models.Index(fields=['timestamp'], name='flooddata_w_timesta_a0e213_idx'),
        ),
        migrations.AddIndex(
            model_name='waterlevelmeasurement',
            index=models.Index(fields=['is_forecast'], name='flooddata_w_is_fore_d679db_idx'),
        ),
    ]
