# Generated by Django 3.2.25 on 2025-03-28 00:40

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Код/Идентификатор')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Местоположение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Точка измерения',
                'verbose_name_plural': 'Точки измерения',
            },
        ),
        migrations.CreateModel(
            name='WaterLevelMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Время измерения')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Значение (м)')),
                ('is_forecast', models.BooleanField(default=False, verbose_name='Прогноз')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='flooddata.measurementpoint', verbose_name='Точка измерения')),
            ],
            options={
                'verbose_name': 'Измерение уровня воды',
                'verbose_name_plural': 'Измерения уровня воды',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FloodZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Геометрия')),
                ('risk_level', models.PositiveSmallIntegerField(choices=[(1, 'Низкий'), (2, 'Средний'), (3, 'Высокий')], default=1, verbose_name='Уровень риска')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_zones', to=settings.AUTH_USER_MODEL, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Зона затопления',
                'verbose_name_plural': 'Зоны затопления',
            },
        ),
        migrations.CreateModel(
            name='FloodEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название события')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Область затопления')),
                ('event_start', models.DateTimeField(verbose_name='Начало события')),
                ('event_end', models.DateTimeField(blank=True, null=True, verbose_name='Окончание события')),
                ('water_level', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Уровень воды (м)')),
                ('source', models.CharField(blank=True, max_length=255, verbose_name='Источник данных')),
                ('is_forecast', models.BooleanField(default=False, verbose_name='Прогноз')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Событие затопления',
                'verbose_name_plural': 'События затопления',
            },
        ),
        migrations.AddIndex(
            model_name='waterlevelmeasurement',
            index=models.Index(fields=['timestamp'], name='flooddata_w_timesta_a0e213_idx'),
        ),
        migrations.AddIndex(
            model_name='waterlevelmeasurement',
            index=models.Index(fields=['is_forecast'], name='flooddata_w_is_fore_d679db_idx'),
        ),
        migrations.AddIndex(
            model_name='floodevent',
            index=models.Index(fields=['event_start', 'event_end'], name='flooddata_f_event_s_2cff25_idx'),
        ),
        migrations.AddIndex(
            model_name='floodevent',
            index=models.Index(fields=['is_forecast'], name='flooddata_f_is_fore_10d280_idx'),
        ),
    ]
