# Generated by Django 3.2.25 on 2025-04-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flooddata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DEMFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dem/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('corrected_file', models.FileField(blank=True, null=True, upload_to='dem_results/')),
                ('accumulation_file', models.FileField(blank=True, null=True, upload_to='dem_results/')),
            ],
        ),
    ]
