# Generated by Django 3.2.25 on 2025-05-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flooddata', '0001_auto_20250508_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='floodanalysis',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID задачи Celery'),
        ),
    ]
