# Generated by Django 5.2.1 on 2025-05-26 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flooddata', '0002_floodanalysis_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floodanalysis',
            name='task_id',
        ),
    ]
