# Generated by Django 5.2.1 on 2025-05-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flooddata', '0003_remove_floodanalysis_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='floodanalysis',
            name='area_both',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь совпадающей воды (кв.км)'),
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='area_only_dem',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь воды только DEM (кв.км)'),
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='area_only_mndwi',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь воды только снимок (кв.км)'),
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='both_path',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Путь к GeoJSON совпадающие'),
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='dem_mask_path',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Путь к маске воды DEM'),
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='mndwi_mask_path',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Путь к маске воды MNDWI'),
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='only_dem_path',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Путь к GeoJSON только DEM'),
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='only_mndwi_path',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Путь к GeoJSON только снимок'),
        ),
    ]
