# Generated by Django 5.2.1 on 2025-05-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flooddata', '0004_floodanalysis_area_both_floodanalysis_area_only_dem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floodanalysis',
            name='green_band',
            field=models.FileField(blank=True, null=True, upload_to='satellite_images/', verbose_name='Канал Green (Band 3)'),
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='swir2_band',
            field=models.FileField(blank=True, null=True, upload_to='satellite_images/', verbose_name='Канал SWIR2 (Band 11)'),
        ),
    ]
