# Generated by Django 5.2.1 on 2025-05-26 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flooddata', '0005_floodanalysis_green_band_floodanalysis_swir2_band'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floodanalysis',
            name='green_band',
        ),
        migrations.RemoveField(
            model_name='floodanalysis',
            name='swir2_band',
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='green_band_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='green_band_analyses', to='flooddata.satelliteimage', verbose_name='Канал Green (Band 3)'),
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='swir2_band_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swir2_band_analyses', to='flooddata.satelliteimage', verbose_name='Канал SWIR2 (Band 11)'),
        ),
        migrations.AlterField(
            model_name='floodanalysis',
            name='satellite_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='flooddata.satelliteimage', verbose_name='Космический снимок'),
        ),
    ]
