# Generated by Django 5.2.1 on 2025-05-31 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flooddata', '0006_remove_floodanalysis_green_band_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterbodyVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Водоёмы', max_length=255, verbose_name='Название слоя')),
                ('file', models.FileField(upload_to='waterbodies/', verbose_name='Векторный файл (shp/geojson)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waterbody_vectors', to=settings.AUTH_USER_MODEL, verbose_name='Загружено')),
            ],
            options={
                'verbose_name': 'Векторный слой водоёмов',
                'verbose_name_plural': 'Векторные слои водоёмов',
                'ordering': ['-upload_date'],
            },
        ),
    ]
