# Generated by Django 5.2.1 on 2025-05-31 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flooddata', '0007_waterbodyvector'),
    ]

    operations = [
        migrations.AddField(
            model_name='floodanalysis',
            name='accumulation_threshold',
            field=models.IntegerField(blank=True, default=1000, null=True, verbose_name='Порог flow accumulation'),
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='permanent_water_method',
            field=models.CharField(choices=[('none', 'Не учитывать'), ('vector', 'Векторный слой водоёмов'), ('accumulation', 'Flow Accumulation (реки/озёра по аккумуляции)')], default='none', max_length=32, verbose_name='Способ постоянных вод'),
        ),
        migrations.AddField(
            model_name='floodanalysis',
            name='waterbody_vector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flooddata.waterbodyvector', verbose_name='Векторный слой водоёмов'),
        ),
    ]
