# Generated by Django 5.2.1 on 2025-05-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flooddata', '0008_floodanalysis_accumulation_threshold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterbodyvector',
            name='file',
        ),
        migrations.AddField(
            model_name='waterbodyvector',
            name='shp_file_path',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Путь к SHP файлу'),
        ),
    ]
